#!/usr/bin/env bash
# Generate the PIA killswitch nftables config at /etc/nftables-pia.conf
#
# This creates a strict killswitch that only allows traffic through
# the VPN tunnel (pia* interface), established connections, loopback,
# SSH (port 22), and a local automation app (port 5173).
# Forward policy blocks all non-VPN routed traffic.
# Optionally sets up NAT masquerade for gateway forwarding.
#
# DNS traffic is NOT explicitly allowed — it must go through the tunnel.
#
# Usage:
#   ./generate_killswitch.sh
#
# Environment variables:
#   PIA_KILLSWITCH_PATH - output path (default: /etc/nftables-pia.conf)
#   PIA_KILLSWITCH_GATEWAY - set to "true" to add NAT masquerade for forwarded
#                            traffic (needed when LXC routes other machines)

set -euo pipefail

: "${PIA_KILLSWITCH_PATH:=/etc/nftables-pia.conf}"
: "${PIA_KILLSWITCH_GATEWAY:=false}"

if (( EUID != 0 )); then
  echo "This script needs to be run as root. Try again with 'sudo $0'"
  exit 1
fi

cat > "$PIA_KILLSWITCH_PATH" <<EOF
#!/usr/sbin/nft -f
# Auto-generated by PIA manual-connections script
# Manual changes will be overwritten on next VPN connection

table inet pia_killswitch {
    chain output {
        type filter hook output priority 0; policy drop;
        oif "lo" accept
        ct state established,related accept
        oifname "pia*" accept
    }
    chain input {
        type filter hook input priority 0; policy drop;
        iif "lo" accept
        ct state established,related accept
        tcp dport 5173 accept
        tcp dport 22 accept
    }
    chain forward {
        type filter hook forward priority 0; policy drop;
        ct state established,related accept
        oifname "pia*" accept
    }
$(if [[ "$PIA_KILLSWITCH_GATEWAY" == "true" ]]; then
echo "    chain postrouting {
        type nat hook postrouting priority 100; policy accept;
        oifname \"pia*\" masquerade
    }"
fi
)
}
EOF

if [[ "$PIA_KILLSWITCH_GATEWAY" == "true" ]]; then
  echo "Gateway NAT masquerade enabled."
fi

echo "Killswitch generated at ${PIA_KILLSWITCH_PATH}"
echo
echo "To apply: sudo nft -f ${PIA_KILLSWITCH_PATH}"
echo "To remove: sudo nft delete table inet pia_killswitch"
